language: r
cache: packages
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8
env:
  global:
  - CXX=g++-8
  - _R_CHECK_FORCE_SUGGESTS_=FALSE
  - _R_CHECK_SYSTEM_CLOCK_=FALSE
  - MAKEFLAGS="-j 2"
before_install:
- mkdir -p ~/.R
- echo "CXX = $CXX" > ~/.R/Makevars
- echo "CXX14 = $CXX" >> ~/.R/Makevars
- echo "CXX14FLAGS = $(R CMD config CXXFLAGS) -fPIC" >> ~/.R/Makevars
matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: oldrel
branches:
  except:
  - /^v?\d+\.\d+/
notifications:
  email: false
  slack:
    secure: ekIWYoZbID67Zla849QdSMwh5ushTS5hp9qCZ0xWR6rNxkddNUu8NeYG/KYK1cj4kf0y/iE6dfcKgF0VbNSVBxGGQOFCWOrxMqASCY61flykwE0cmCrTPv4XUmR5IEp/tMB1VVX5PAZslbDEwah4deKOnBVZykFudMnd0CLM1ojOytV9HhCUU0LumSFvRlw9Uewj9DCPmBxNIAfBHCTG2xPVCPdsxOmO90FGcM/M2ax3aNW0s89TfsvW8OTOW0RW25wSmwfKSBilFookagO05m9qQ5iEmAT7CcQhzkbXUKx2shAL9Tu3cROByhcuhT6pzyl8XP1ip3hhywyQqOX1xg67WDybUBQ7ZZQmCCvN9vuu+ltI3x6v2ZjrTGvBqDLSTQfQhIzgLS8uCE7ci749dS4wq6U8Ttnvfl3VigdJjrTDyarmxhUWI5FNVdMGNlvCI9q3k3GJCOvjQ95mj9hbM0gs3l/hw8qQVYiPBUlnOXNFh5f90n2UsDOPULrym7b/0KiJrf9O7ynsqapQ8B/ZO4H6w4b9RSCdnNjMQogDPn4hOUCzdZ+ol86V6rAYtMsdA9jyqWGt9XOjF46gqBoRTLgEdk8nmdEkwWhHmIz+tnoigns46tbftZD17O2U01x7OX8Rm8mU0cIxC2efZ2m2kOphYhOFNCLgQmGwbUTmfgA=
